### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by gh-newbie** [dmaslov/flask-blog#13]
Dear Sir:

　I install this on CentOS 7 and mongodb 3.0x,
when I python web.py, show error message in console:

//
Error type: TypeError in file: post.py on line: 103
Error details: list indices must be integers, not str
//

After I try to create a user account on Web,
it error with "create user user error" and error message in console

//
Error type: TypeError in file: user.py on line: 152
Error details: __init__() got an unexpected keyword argument 'safe'
//

My config in config.py:

//
#CONNECTION_STRING = "mongodb://localhost" # replace it with your settings
CONNECTION_STRING = "mongodb://acc:pwd@localhost:27017/dbname

#DATABASE = CONNECTION.blog
DATABASE = CONNECTION.dbname
//

How should I fix the problem?

Thank you

**Comment by gh-newbie** [comment]
fix My config in config.py:

#CONNECTION_STRING = "mongodb://localhost"  # replace it with your settings
CONNECTION_STRING = "mongodb://acc:pwd@localhost:27017/dbname

#DATABASE = CONNECTION.blog
DATABASE = CONNECTION.dbname

**Comment by garni-kh** [comment]
i think it dose  not work with python3 try this https://github.com/garni-kh/flask-blog

**Comment by gh-newbie** [comment]
but....

# python -V
Python 2.7.5

囧...

**Comment by garni-kh** [comment]
sury it is my mistake ,i think your mongoldb version is python version

let see i install it very easy

**Comment by gh-newbie** [comment]
I am counting on you ..

**Comment by garni-kh** [comment]
i saw my config.py 
CONNECTION_STRING = "mongodb://localhost" 
just this 
uncomment and comment your change and try

**Comment by gh-newbie** [comment]
Because I use auth with mongodb,
so I must type with acc:pwd and /dbname..

or
CONNECTION_STRING = "mongodb://localhost" 

show the error message on console

#
Error type: OperationFailure in file: post.py on line: 28
Error details: database error: not authorized for query on flaskblog.posts
#

#
Error type: OperationFailure in file: post.py on line: 101
Error details: command SON([('aggregate', u'posts'), ('pipeline', [{'$unwind': '                                              $tags'}, {'$group': {'count': {'$sum': 1}, '_id': '$tags'}}, {'$sort': {'count':                                               -1}}, {'$limit': 10}, {'$project': {'count': 1, '_id': 0, 'title': '$_id'}}]),                                               ('cursor', {})]) on namespace flaskblog.$cmd failed: not authorized on flaskblog                                               to execute command { aggregate: "posts", pipeline: [ { $unwind: "$tags" }, { $g                                              roup: { count: { $sum: 1 }, _id: "$tags" } }, { $sort: { count: -1 } }, { $limit                                              : 10 }, { $project: { count: 1, _id: 0, title: "$_id" } } ], cursor: {} }
#

**Comment by garni-kh** [comment]
try this 
CONNECTION_STRING = "mongodb://acc:pwd@localhost:27017"

**Comment by garni-kh** [comment]
CONNECTION_STRING = "mongodb://acc:pwd@localhost:27017/dbname  
are you forget " in end of line
CONNECTION_STRING = "mongodb://acc:pwd@localhost:27017/dbname"

**Comment by gh-newbie** [comment]
config.py

CONNECTION_STRING = "mongodb://<acc>:<pwd>@localhost:27017"
'''Leave this as is if you dont have other configuration'''
#DATABASE = CONNECTION.blog
DATABASE = CONNECTION.<dbname>
or 
DATABASE = CONNECTION.blog
#DATABASE = CONNECTION.<dbname>
or
CONNECTION_STRING = "mongodb://<acc>:<pwd>@localhost:27017/<dbname>"
DATABASE = CONNECTION.blog

all the same Error Message:

#
Error type: OperationFailure in file: post.py on line: 28
Error details: command SON([('saslStart', 1), ('mechanism', 'SCRAM-SHA-1'), ('payload', Binary('n,,n=flaskblog,r=MDg0MjU5ODExMzI5OA==', 0)), ('autoAuthorize', 1)]) on namespace admin.$cmd failed: Authentication failed.
#

#
Error type: OperationFailure in file: post.py on line: 101
Error details: command SON([('saslStart', 1), ('mechanism', 'SCRAM-SHA-1'), ('payload', Binary('n,,n=flaskblog,r=NzQxMjM5MTUwMzEy', 0)), ('autoAuthorize', 1)]) on namespace admin.$cmd failed: Authentication failed.
#

**Comment by gh-newbie** [comment]
mongo with my database and user account info:

> use 'dbname'
switched to db 'dbname'
> show users
{
        "_id" : "'dbname'.'acc'",
        "user" : "'acc'",
        "db" : "'dbname'",
        "roles" : [
                {
                        "role" : 'readWrite',
                        "db" : "'dbname'"
                }
        ]

**Comment by garni-kh** [comment]
it is my config.py



import pymongo
import os

CONNECTION_STRING = "mongodb://localhost"  # replace it with your settings
CONNECTION = pymongo.MongoClient(CONNECTION_STRING)

'''Leave this as is if you dont have other configuration'''
DATABASE = CONNECTION.blog
POSTS_COLLECTION = DATABASE.posts
USERS_COLLECTION = DATABASE.users
SETTINGS_COLLECTION = DATABASE.settings

SECRET_KEY = ""
basedir = os.path.abspath(os.path.dirname(__file__))
secret_file = os.path.join(basedir, '.secret')
if os.path.exists(secret_file):
    # Read SECRET_KEY from .secret file
    f = open(secret_file, 'r')
    SECRET_KEY = f.read().strip()
    f.close()
else:
    # Generate SECRET_KEY & save it away
    SECRET_KEY = os.urandom(24)
    f = open(secret_file, 'w')
    f.write(SECRET_KEY)
    f.close()
    # Modeify .gitignore to include .secret file
    gitignore_file = os.path.join(basedir, '.gitignore')
    f = open(gitignore_file, 'a+')
    if '.secret' not in f.readlines() and '.secret\n' not in f.readlines():
        f.write('.secret\n')
    f.close()

LOG_FILE = "app.log"

DEBUG = True  # set it to False on production

**Comment by gh-newbie** [comment]
so you didn;t create a flask_blog db and user account in mongodb?

**Comment by garni-kh** [comment]
yes ,i think for bloging it didn't necessary you do every think and privilege in blog

**Comment by garni-kh** [comment]
now i don't have mongodb install ,but this setting work for me.

**Comment by gh-newbie** [comment]
oh oh... Ok... I try to set auth=false in mongodb now and try again...
but hope author or someone can help me to check if can fix the problem ,,, ~_~

**Comment by garni-kh** [comment]
i try install mongo tomorrow and try agin

**Comment by gh-newbie** [comment]
I stop mongodb then python web.py
#
Error type: ServerSelectionTimeoutError in file: post.py on line: 28
Error details: localhost:27017: [Errno 111] Connection refused
#
囧...
i already don't know how to do...

Thank you for help, waiting you...

**Comment by dmaslov** [comment]
@gh-newbie
Sorry for delayed answer. Big thanks for bug hunting!
Everything should work fine now.
Please try again and open this issue if something goes wrong.

**Comment by gh-newbie** [comment]
I update post.py, user.py , web.py, then python web.py.
I type the web ip and show the error message:



TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last)

    File "/home/blog/flask-blog/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/blog/flask-blog/env/lib/python2.7/site-packages/flask/app.py", line 1825, in wsgi_app

    ctx.auto_pop(error)

    File "/home/blog/flask-blog/env/lib/python2.7/site-packages/flask/ctx.py", line 370, in auto_pop

    (exc is not None and self.app.preserve_context_on_exception):

    File "/home/blog/flask-blog/env/lib/python2.7/site-packages/flask/app.py", line 559, in preserve_context_on_exception

    rv = self.config['PRESERVE_CONTEXT_ON_EXCEPTION']

    TypeError: 'NoneType' object has no attribute '__getitem__'

Anything I lose?
