### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by gh-ghost** [dmaslov/flask-blog#14]
I come again ...Orz

I update post.py, user.py , web.py, then python web.py.
I type the web ip and saw the error message:

TypeError: 'NoneType' object has no attribute '**getitem**'
Traceback (most recent call last)

```
File "/flask-blog/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__

return self.wsgi_app(environ, start_response)

File "/flask-blog/env/lib/python2.7/site-packages/flask/app.py", line 1825, in wsgi_app

ctx.auto_pop(error)

File "/flask-blog/env/lib/python2.7/site-packages/flask/ctx.py", line 370, in auto_pop

(exc is not None and self.app.preserve_context_on_exception):

File "/flask-blog/env/lib/python2.7/site-packages/flask/app.py", line 559, in preserve_context_on_exception

rv = self.config['PRESERVE_CONTEXT_ON_EXCEPTION']

TypeError: 'NoneType' object has no attribute '__getitem__'
```

Anything I did wrong?

**Comment by dmaslov** [comment]
Hey, @gh-newbie !
Checked out everything one more time. Don't see any issues.
Could you please remove your database and clone the project again?

``` bash
git clone https://github.com/dmaslov/flask-blog.git

cd flask-blog

virtualenv --no-site-packages ./env

source ./env/bin/activate

pip install -r requirements.txt
```

**Comment by gh-ghost** [comment]
Hi:

　Seems ok already, I know where is my wrong:
config.py:

CONNECTION_STRING = "mongodb://'acc':'pwd'@127.0.0.1:27017/"

I added my blog db in the end

CONNECTION_STRING = "mongodb://'acc':'pwd'@127.0.0.1:27017/'dbname'"

so I got error...

Thank you.

ps:But... how to delete a post and a user?

**Comment by garni-kh** [comment]
:)

**Comment by dmaslov** [comment]
@gh-newbie 
[Here](http://docs.mongodb.org/manual/) is the official tutorial how to deal with mongoDB.
Other useful [tutorial](http://www.tutorialspoint.com/mongodb/index.htm) with examples
You could use command `db.user.drop()` `db.post.drop()`
**Also you could drop your DB again and start from scratch!** `dbname.dropDatabase()`
I recommend to start from scratch
